version: '3'
services:
  stardog:
    image: stardog/stardog
    ports:
      - "5280:5280"
    volumes:
      - ./stardog-home/:/var/opt/stardog
    stdin_open: true
    tty: true
  studio:
    image: stardog/stardog-studio:current
    ports:
      - "8888:8080"
    depends_on:
      - "stardog"
